export const audioList = {
  click: new Audio("assets/click.mp3"),
  start: new Audio("assets/start.mp3"),
  shabash: new Audio("assets/shabash.mp3"),
  over: new Audio("assets/over.mp3"),
  wrong: new Audio("assets/wrong.mp3"),
  correct: new Audio("assets/correct.mp3"),
  bg: new Audio("assets/bg.mp3")
};
export const categories = {
  animals: {
    words: [
      "elephant",
      "tiger",
      "lion",
      "monkey",
      "crocodile",
      "rhinoceros",
      "cheetah",
      "bear",
      "wolf",
      "penguin",
    ],
    hints: [
      "The largest land animal, often seen in Indian zoos",
      "A big cat with stripes, found in India’s jungles",
      "Known as the 'king of the jungle', found in Indian national parks",
      "A tree-climbing primate, commonly seen in Indian forests",
      "A reptile with a long snout, found in Indian rivers",
      "An animal with a horn on its nose, found in Indian reserves",
      "The fastest land animal, found in Africa",
      "A large carnivorous mammal with fur, found in zoos",
      "A wild animal known for howling, not native to India",
      "A flightless bird from Antarctica, not seen in India",
    ],
  },
  birds: {
    words: [
      "peacock",
      "sparrow",
      "eagle",
      "parrot",
      "owl",
      "swan",
      "flamingo",
      "woodpecker",
      "kingfisher",
      "pigeon",
    ],
    hints: [
      "India’s national bird, with colorful feathers",
      "A small bird found in most Indian cities",
      "A bird of prey with sharp eyes, seen in India’s forests",
      "A colorful bird that can mimic human speech, often kept as a pet",
      "A bird known for its night calls, found in Indian forests",
      "A graceful white bird often seen in lakes",
      "A pink bird with long legs, found in Indian wetlands",
      "A bird that pecks on trees, found in Indian forests",
      "A bird known for diving into water, found in Indian rivers",
      "A common city bird, found everywhere in India",
    ],
  },
  indian: {
    words: [
      "ganga",
      "mumbai",
      "delhi",
      "tajmahal",
      "kerala",
      "rajasthan",
      "karnataka",
      "sikkim",
      "chennai",
      "kolkata",
      "jaipur",
      "agra",
      "meghalaya",
      "punjab",
      "assam",
      "goa",
      "hyderabad",
      "bengaluru",
      "himachal",
      "ladakh",
      "lata-mangeshkar",
      "kishore-kumar",
      "arijit-singh",
      "mohammed-rafi",
      "aasha-bhosle",
      "sachin-tendulkar",
      "ms-dhoni",
      "pv-sindhu",
      "abhinav-bindra",
      "virat-kohli",
      "chandragupta-maurya",
      "samudragupta",
      "rudradaman",
      "qutub-minar",
      "red-fort",
      "hampi",
      "sanchi-stupas",
      "konark-sun-temple",
    ],
    hints: [
      "A sacred river in India, important in Hinduism",
      "The city known as the financial capital of India, on the west coast",
      "The capital city of India, famous for its monuments",
      "A white marble mausoleum in Agra, UNESCO World Heritage site",
      "A state with beautiful backwaters and greenery in southern India",
      "A desert state famous for its palaces and forts",
      "A state with the city of Bengaluru, known for technology",
      "A small state in the northeast with beautiful landscapes",
      "A major city in southern India, formerly called Madras",
      "The city known for its cultural richness, in eastern India",
      "The city famous for its pink buildings and historic forts",
      "The city where the Taj Mahal is located",
      "A state known for its heavy rains and scenic hills",
      "A state known for its rich culture and Punjabi traditions",
      "A state in the northeast famous for tea gardens",
      "A small state with beautiful beaches and lively casinos",
      "A city known for its technology sector and historic sites",
      "A major tech hub in southern India, known for its gardens",
      "A state with beautiful landscapes and hill stations",
      "A region known for its stunning landscapes and Buddhist monasteries",
      "A legendary singer with a long career in Indian music",
      "A famous playback singer known for his unique voice",
      "A contemporary singer known for his romantic songs",
      "An iconic playback singer with a long career in Indian cinema",
      "A famous playback singer and sister of Lata Mangeshkar",
      "A legendary cricketer known as the 'Little Master'",
      "A former captain of the Indian cricket team known for his leadership",
      "An Olympic medalist in badminton from India",
      "An Olympic gold medalist in shooting from India",
      "A prominent cricketer and former captain of the Indian team",
      "The founder of the Maurya Empire in ancient India",
      "A Gupta emperor known for his military achievements",
      "A king known for his inscriptions from the Western Kshatrapas",
      "A historic monument in Delhi built during the Mughal era",
      "A famous red sandstone fort in Delhi built by Shah Jahan",
      "An ancient city in Karnataka known for its ruins and temples",
      "A group of ancient Buddhist monuments in Madhya Pradesh",
      "A famous sun temple in Odisha known for its detailed carvings",
    ],
  },
  fruits: {
    words: [
      "apple",
      "banana",
      "orange",
      "strawberry",
      "grape",
      "pineapple",
      "mango",
      "watermelon",
      "kiwi",
      "pomegranate",
    ],
    hints: [
      "A fruit that can be red or green, often eaten as a snack",
      "A long yellow fruit, commonly used in smoothies",
      "A round orange fruit, rich in Vitamin C",
      "A red fruit with tiny seeds on the outside, used in desserts",
      "Small purple or green fruits, often used in wine",
      "A tropical fruit with a spiky exterior, used in fruit salads",
      "A sweet, juicy fruit with orange flesh, known as the 'king of fruits'",
      "A large fruit with green skin and red flesh, very refreshing",
      "A small brown fruit with green flesh inside",
      "A fruit with many seeds inside and a tough outer skin",
    ],
  },
  vegetables: {
    words: [
      "carrot",
      "potato",
      "tomato",
      "cucumber",
      "spinach",
      "cauliflower",
      "pepper",
      "onion",
      "garlic",
      "peas",
      "corn",
      "eggplant",
      "zucchini",
      "lettuce",
      "beetroot",
      "sweetpotato",
      "radish",
    ],
    hints: [
      "An orange root vegetable, often used in salads and curries",
      "A starchy tuber, used in many Indian dishes like aloo gobi",
      "A red fruit often used in gravies and curries",
      "A long green vegetable, used in salads and raita",
      "A leafy green vegetable, used in saag and palak dishes",
      "A white vegetable, used in dishes like aloo-gobhi",
      "A vegetable that comes in many colors, used in curries",
      "A vegetable that makes you cry when cut, used in bhajis and curries",
      "A strong-smelling vegetable used in flavoring dishes",
      "Small green round seeds, used in curries and pulao",
      "A yellow vegetable often eaten as a side dish or in soups",
      "A purple vegetable, used in bhartas and curries",
      "A green squash used in many Indian dishes",
      "A leafy green vegetable used in salads and sandwiches",
      "A red root vegetable used in salads and curries",
      "A sweet orange tuber often used in chaat and desserts",
      "A small round vegetable with a spicy taste, used in salads",
    ],
  },
};
